name: Publish hql-tag to the npm registry
on:
  push:
    branches:
      - master
jobs:
    build:
      if: github.actor == 'repo-owner'
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}